# Generated by Django 6.0.5 on 2026-06-02 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customerprofile_created_at_ownerprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownerprofile',
            options={'ordering': ['-created_at']},
        ),
    ]
