# Generated by Django 5.2 on 2026-06-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='announcements/%Y/%m/'),
        ),
    ]
