# Generated by Django 6.0.5 on 2026-06-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter / X'), ('youtube', 'YouTube'), ('tiktok', 'TikTok')], max_length=20, unique=True, verbose_name='Platform')),
                ('url', models.URLField(blank=True, default='', help_text='Paste the full URL (e.g. https://facebook.com/yourpage). Leave blank to hide the link.', verbose_name='Profile URL')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['platform'],
            },
        ),
    ]
