# Generated by Django 6.0.5 on 2026-06-01 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('luxury', 'Luxury'), ('hatchback', 'Hatchback'), ('truck', 'Truck'), ('van', 'Van'), ('wagon', 'Wagon')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['is_approved', 'is_available', 'created_at'], name='cars_car_is_appr_6a45ee_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['car_type', 'is_available'], name='cars_car_car_typ_22c508_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['price_per_day'], name='cars_car_price_p_df7c78_idx'),
        ),
        migrations.AddIndex(
            model_name='carimage',
            index=models.Index(fields=['car', 'is_primary', 'id'], name='cars_carima_car_id_4835d9_idx'),
        ),
    ]
