# Generated by Django 6.0.5 on 2026-06-11 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_price_per_day_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('car', 'Car'), ('loader', 'Loader'), ('dumper', 'Dumper')], db_index=True, default='car', max_length=20),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['category', 'is_available'], name='cars_car_categor_bda24c_idx'),
        ),
    ]
