# Generated by Django 6.0.5 on 2026-06-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_category_luxury_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('muv_mpv', 'MUV/MPV'), ('crossover', 'Crossover'), ('convertible', 'Convertible'), ('coupe', 'Coupe'), ('pickup_truck', 'Pickup Truck'), ('luxury_sedan', 'Luxury Sedan'), ('luxury_suv', 'Luxury SUV'), ('sports_car', 'Sports Car'), ('luxury_convertible', 'Luxury Convertible'), ('luxury_coupe', 'Luxury Coupe'), ('limousine', 'Limousine'), ('electric_luxury', 'Electric Luxury'), ('luxury_crossover', 'Luxury Crossover'), ('mini_truck', 'Mini Truck'), ('pickup_loader', 'Pickup Loader'), ('container_truck', 'Container Truck'), ('tipper_dumper', 'Tipper/Dumper'), ('flatbed_truck', 'Flatbed Truck'), ('refrigerated_truck', 'Refrigerated Truck'), ('tanker_truck', 'Tanker Truck'), ('crane_truck', 'Crane Truck')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('car', 'Car'), ('luxury_car', 'Luxury Car'), ('loader', 'Loader')], db_index=True, default='car', max_length=20),
        ),
    ]
