# Generated by hand to map old car type and category values

from django.db import migrations

def map_old_types_and_categories(apps, schema_editor):
    Car = apps.get_model('cars', 'Car')
    
    # 1. Update categories: dumper -> loader
    Car.objects.filter(category='dumper').update(category='loader')
    
    # 2. Update car types:
    # luxury -> luxury_sedan
    Car.objects.filter(car_type='luxury').update(car_type='luxury_sedan')
    # truck -> mini_truck
    Car.objects.filter(car_type='truck').update(car_type='mini_truck')
    # van -> muv_mpv
    Car.objects.filter(car_type='van').update(car_type='muv_mpv')
    # wagon -> hatchback
    Car.objects.filter(car_type='wagon').update(car_type='hatchback')


def rollback_mapping(apps, schema_editor):
    # Optional reverse mapping if needed
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_car_type_alter_car_category'),
    ]

    operations = [
        migrations.RunPython(map_old_types_and_categories, rollback_mapping),
    ]
