# Generated by Django 6.0.5 on 2026-06-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingmessage",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bookingmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("system", "System"),
                    ("location", "Location"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
