# Generated by Django 6.0.5 on 2026-06-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_add_location_message_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingmessage",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="message_attachments/%Y/%m/"
            ),
        ),
        migrations.AlterField(
            model_name="bookingmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("system", "System"),
                    ("location", "Location"),
                    ("attachment", "Attachment"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
